behaviors:
  WalkerAgent:
    trainer_type: ppo

    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0001

    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        
    max_steps: 4800000
    time_horizon: 1000
    summary_freq: 160000
